name: Hello world action

on: [push, workflow_call]
  # - workflow_call:
runs:
  using: "composite"
  steps:
    - name: Hello
      run: echo "Hello, world!"
      id: hello
    - name: World
      run: echo "Hello, world!"
      if: steps.hello.outputs.hello == 'Hello, world!'

