name: Hello world action

on: [push, workflow_call]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, world!"
        id: hello
      - name: World
        run: echo "Hello, world!"
        if: steps.hello.outputs.hello == 'Hello, world!'
